# Generated by Django 4.2 on 2024-04-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DistanceMatrix",
            fields=[
                ("oid", models.AutoField(primary_key=True, serialize=False)),
                ("distance_matrix_id", models.CharField(max_length=255)),
                ("start_location_id", models.CharField(max_length=255)),
                ("start_location_name_en", models.CharField(max_length=255)),
                ("start_location_name_bn", models.CharField(max_length=255)),
                ("end_location_id", models.CharField(max_length=255)),
                ("end_location_name_en", models.CharField(max_length=255)),
                ("end_location_name_bn", models.CharField(max_length=255)),
                ("distance", models.FloatField()),
                ("remarks", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TaDaRateSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField()),
                (
                    "daily_allowance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
