# Generated by Django 4.1 on 2023-01-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatbotVisitorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_ip", models.CharField(blank=True, max_length=20, null=True)),
                ("visitors_msg", models.CharField(max_length=255)),
                ("bot_msg", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name_plural": "Chatbot Visitor Message",
            },
        ),
    ]
