# Generated by Django 4.1 on 2023-01-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatbotVisitorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_ip", models.CharField(blank=True, max_length=20, null=True)),
                ("visitors_msg", models.CharField(max_length=255)),
                ("bot_msg", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name_plural": "Chatbot Visitor Message",
            },
        ),
        migrations.CreateModel(
            name="CSOVisitorConvoInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_slug", models.CharField(max_length=25)),
                (
                    "cso_email",
                    models.CharField(
                        max_length=60, verbose_name="Customer Support Officer Email"
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "is_connected",
                    models.BooleanField(
                        default=False, verbose_name="Is CSO connected?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Conversation created at"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CSO Visitor Conversation Information",
            },
        ),
        migrations.CreateModel(
            name="CSOVisitorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255, null=True)),
                ("user_identity", models.CharField(max_length=25)),
                ("room_slug", models.CharField(max_length=25)),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name_plural": "CSO Visitor Messages",
            },
        ),
        migrations.CreateModel(
            name="CustomerSupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_ip", models.CharField(blank=True, max_length=20, null=True)),
                ("room_slug", models.SlugField(unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name_plural": "Customer Support Request",
            },
        ),
    ]
