# Generated by Django 4.1 on 2023-01-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_ip", models.CharField(blank=True, max_length=20, null=True)),
                ("room_slug", models.SlugField(unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name_plural": "Customer Support Request",
            },
        ),
    ]
