# Generated by Django 4.1 on 2023-01-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_customersupportrequest_visitor_session_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSupportUserOnline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cso_email", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "visitor_session_uuid",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("room_slug", models.CharField(max_length=25)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="User active"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Joined at"),
                ),
                (
                    "last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last activity"),
                ),
            ],
            options={
                "verbose_name_plural": "Customer Support (Chat) CSO-Visitor Online",
            },
        ),
    ]
