# Generated by Django 4.1.7 on 2023-03-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userchatbotsocket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='csovisitorconvoinfo',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='The user cancelled the chat-conversation', verbose_name='Chat cancelled'),
        ),
    ]
