# Generated by Django 4.1 on 2023-01-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_customersupportrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSOVisitorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255, null=True)),
                ("user_identity", models.CharField(max_length=25)),
                ("room_slug", models.CharField(max_length=25)),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name_plural": "CSO Visitor Messages",
            },
        ),
    ]
