# Generated by Django 4.2 on 2023-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_csovisitorconvoinfo_is_cleared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csovisitorconvoinfo',
            name='is_dismissed',
            field=models.BooleanField(default=False, help_text='CSO marks the issue as dismissed, displays boolean values'),
        ),
        migrations.AlterField(
            model_name='csovisitorconvoinfo',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='CSO marks the issue as resolved, displays boolean values'),
        ),
    ]
