# Generated by Django 4.2.1 on 2023-06-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_csovisitorconvoinfo_is_cleared_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemarkResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created remarks after providing solution",
                    ),
                ),
                (
                    "cso_user_convo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="home.csovisitorconvoinfo",
                    ),
                ),
            ],
        ),
    ]
