# Generated by Django 4.1.7 on 2023-02-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chatsupportuserconnectedchannels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsupportuseronline',
            options={'verbose_name_plural': 'Customer Support (Chat) CSO-Visitor Chat Online'},
        ),
    ]
