# Generated by Django 4.2.1 on 2023-07-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remarkresolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="customersupportrequest",
            name="is_detached",
            field=models.BooleanField(
                default=False,
                help_text="Mark as detached if the CSO mark the 'CustomerSupportRequest' as resolved or dismissed",
                verbose_name="Detached",
            ),
        ),
        migrations.AddField(
            model_name="customersupportrequest",
            name="is_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="Mark as dismissed if the CSO marked the coordinating convoInfo as dismissed",
                verbose_name="Dismissed",
            ),
        ),
    ]
