# Generated by Django 4.1.7 on 2023-02-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_chatsupportuseronline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportrequest',
            name='assigned_cso',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
