# Generated by Django 4.1.7 on 2023-03-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customersupportrequest_assigned_cso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csovisitorconvoinfo',
            name='is_connected',
            field=models.BooleanField(default=False, help_text="The CSO has marked this conversation as resolved if it's displayed 'False'", verbose_name='Is CSO connected?'),
        ),
    ]
