# Generated by Django 4.2.1 on 2023-07-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_customersupportrequest_is_detached_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="csovisitorconvoinfo",
            name="is_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="CSO marks the issue as dismissed, displays boolean values",
            ),
        ),
        migrations.AlterField(
            model_name="csovisitorconvoinfo",
            name="is_resolved",
            field=models.BooleanField(
                default=False,
                help_text="CSO marks the issue as resolved, displays boolean values",
            ),
        ),
    ]
