# Generated by Django 4.2 on 2023-06-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remarkresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportrequest',
            name='is_dismissed',
            field=models.BooleanField(default=False, help_text='Marked as dismissed if the CSO marked the coordinating convoInfo as dismissed'),
        ),
    ]
