# Generated by Django 4.2 on 2023-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customersupportrequest_is_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportrequest',
            name='is_detached',
            field=models.BooleanField(default=False, help_text="Mark as detached if the CSO mark the 'CustomerSupportRequest' as resolved or dismissed", verbose_name='Detached'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='is_dismissed',
            field=models.BooleanField(default=False, help_text='Mark as dismissed if the CSO marked the coordinating convoInfo as dismissed', verbose_name='Dismissed'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Mark as resolved if the CSO marked the coordinating convoInfo as resolved', verbose_name='Resolved'),
        ),
    ]
