# Generated by Django 4.1.7 on 2023-03-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_csovisitorconvoinfo_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportrequest',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Marked as resolved if the CSO marked the coordinating convoInfo as resolved'),
        ),
    ]
