# Generated by Django 4.2 on 2023-07-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customersupportrequest_is_detached_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csovisitorconvoinfo',
            name='is_connected',
            field=models.BooleanField(default=False, help_text="The CSO has marked this conversation as resolved/dismissed if it's displayed 'False'", verbose_name='Is CSO connected?'),
        ),
    ]
