# Generated by Django 4.1.7 on 2023-03-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customersupportrequest_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportrequest',
            name='regustered_user_email_normalized',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='User Email (normalized)'),
        ),
    ]
