# Generated by Django 4.2.1 on 2023-07-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_customersupportrequest_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="csovisitormessage",
            options={"verbose_name_plural": "HDO Visitor Messages"},
        ),
    ]
