# Generated by Django 4.1.7 on 2023-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_customersupportrequest_regustered_user_email_normalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersupportrequest',
            name='regustered_user_email_normalized',
        ),
        migrations.AddField(
            model_name='customersupportrequest',
            name='registered_user_email_normalized',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='User Email (normalized)'),
        ),
    ]
