# Generated by Django 4.2.1 on 2023-07-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_csovisitormessage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="csovisitorconvoinfo",
            options={"verbose_name_plural": "HDO Visitor Conversation Information"},
        ),
        migrations.AlterField(
            model_name="csovisitorconvoinfo",
            name="cso_email",
            field=models.CharField(
                max_length=60, verbose_name="Help Desk Officer Email"
            ),
        ),
        migrations.AlterField(
            model_name="csovisitorconvoinfo",
            name="is_cleared",
            field=models.BooleanField(
                default=False,
                help_text="The HDO removed/cleared the associate msg-req from the CSR List, thus the conversation will be marked as cleared",
                verbose_name="Associate msg-req is removed",
            ),
        ),
        migrations.AlterField(
            model_name="csovisitorconvoinfo",
            name="is_connected",
            field=models.BooleanField(
                default=False,
                help_text="The HDO has marked this conversation as resolved if it's displayed 'False'",
                verbose_name="Is HDO connected?",
            ),
        ),
        migrations.AlterField(
            model_name="csovisitorconvoinfo",
            name="is_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="HDO marks the issue as dismissed, displays boolean values",
            ),
        ),
        migrations.AlterField(
            model_name="csovisitorconvoinfo",
            name="is_resolved",
            field=models.BooleanField(
                default=False,
                help_text="HDO marks the issue as resolved, displays boolean values",
            ),
        ),
    ]
