# Generated by Django 4.1.7 on 2023-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_customersupportrequest_regustered_user_email_normalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupportrequest',
            name='registered_user_email_normalized',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='User Email (normalized)'),
        ),
    ]
