# Generated by Django 4.1.7 on 2023-03-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_customersupportrequest_registered_user_email_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='csovisitorconvoinfo',
            name='registered_user_email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='User Email'),
        ),
    ]
