# Generated by Django 4.2.1 on 2023-07-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_remarkresolution_cso_user_convo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsupportuserconnectedchannels",
            options={"verbose_name_plural": "HDO-User Channels"},
        ),
        migrations.AlterModelOptions(
            name="chatsupportuseronline",
            options={"verbose_name_plural": "HDO-User Online"},
        ),
        migrations.AlterField(
            model_name="chatsupportuserconnectedchannels",
            name="cso_email",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="HDO email"
            ),
        ),
        migrations.AlterField(
            model_name="chatsupportuseronline",
            name="cso_email",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="HDO email"
            ),
        ),
    ]
