# Generated by Django 4.1.7 on 2023-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_csovisitorconvoinfo_registered_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportrequest',
            name='issue_by_oid',
            field=models.CharField(blank=True, default='6f8b28a3-0e2e-4f06-b3eb-6f7b4e2da5ac', help_text='Remove the default oid later (when the bot will create the issue & get the response)', max_length=60, null=True),
        ),
    ]
