# Generated by Django 4.2.1 on 2023-11-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_chatsupportuserconnectedchannels_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customersupportrequest",
            name="chatbot_socket_id",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
