# Generated by Django 4.2 on 2023-07-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_customersupportrequest_is_detached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupportrequest',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Mark as resolved if the HDO marked the coordinating convoInfo as resolved', verbose_name='Resolved'),
        ),
    ]
