# Generated by Django 4.2 on 2023-07-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_csovisitorconvoinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarkresolution',
            name='cso_user_convo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.csovisitorconvoinfo', verbose_name='HDO-User Conversation'),
        ),
    ]
