# Generated by Django 4.2 on 2023-07-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_remarkresolution_cso_user_convo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsupportuserconnectedchannels',
            options={'verbose_name_plural': 'HDO-Visitor Channels'},
        ),
        migrations.AlterModelOptions(
            name='chatsupportuseronline',
            options={'verbose_name_plural': 'HDO-Visitor Chat Online'},
        ),
        migrations.AlterField(
            model_name='chatsupportuserconnectedchannels',
            name='cso_email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='HDO email'),
        ),
        migrations.AlterField(
            model_name='chatsupportuseronline',
            name='cso_email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='HDO email'),
        ),
    ]
