# Generated by Django 4.2 on 2023-07-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_chatsupportuserconnectedchannels_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsupportuserconnectedchannels',
            options={'verbose_name_plural': 'HDO-User Channels'},
        ),
        migrations.AlterModelOptions(
            name='chatsupportuseronline',
            options={'verbose_name_plural': 'HDO-User Chat Online'},
        ),
    ]
