# Generated by Django 4.2 on 2023-07-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_chatsupportuserconnectedchannels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsupportuserconnectedchannels',
            options={'verbose_name_plural': 'HDO-User Channels'},
        ),
    ]
