# Generated by Django 4.2 on 2023-07-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_chatsupportuserconnectedchannels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsupportuseronline',
            options={'verbose_name_plural': 'HDO-User Online'},
        ),
    ]
