# Generated by Django 4.1.7 on 2023-03-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='User Email')),
                ('user_address', models.TextField(blank=True, null=True, verbose_name='User Address')),
                ('user_name_bn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ইউজার নাম (বাংলা)')),
                ('user_father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Name')),
                ('user_mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mother Name')),
                ('user_NID_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='NID no.')),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User (Staff, CSO, Admin, User, Superuser)'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
