# Generated by Django 4.1 on 2023-01-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticationApp", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="initial_password",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
