# Generated by Django 4.1.7 on 2023-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0002_user_profile_alter_user_options_user_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profilePicture/default_avatar.png', upload_to='profilePicture'),
        ),
    ]
