# Generated by Django 4.1 on 2023-01-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticationApp", "0003_user_initial_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
    ]
