# Generated by Django 4.1.7 on 2023-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_signin_token_tms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='User Email')),
                ('user_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token')),
                ('token_type', models.EmailField(blank=True, max_length=10, null=True, verbose_name='Token Type')),
            ],
            options={
                'verbose_name_plural': 'User Signin Token (TMS)',
            },
        ),
    ]
