# Generated by Django 4.1.7 on 2023-03-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0004_user_signin_token_tms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signin_token_tms',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='User id (TMS)'),
        ),
    ]
