# Generated by Django 4.1.7 on 2023-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0005_user_signin_token_tms_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signin_token_tms',
            name='user_id',
            field=models.CharField(blank=True, help_text="TMS 'user_id' is the 'uesrname' of the COS", max_length=200, null=True, verbose_name='User id (TMS)'),
        ),
    ]
