# Generated by Django 4.2 on 2023-05-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user_signin_token_tms',
            name='user_token',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Access Token'),
        ),
    ]
