# Generated by Django 4.2 on 2023-05-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0008_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signin_token_tms',
            name='user_token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Access Token'),
        ),
    ]
