# Generated by Django 4.2 on 2023-07-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0010_user_profile_district_name_user_profile_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user_organization_name',
            new_name='user_organization',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='district_name',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Division'),
        ),
    ]
