# Generated by Django 4.2.1 on 2023-07-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticationApp", "0010_alter_user_signin_token_tms_token_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="District"
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="division",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Division"
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="user_organization",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Organization"
            ),
        ),
    ]
