# Generated by Django 4.2 on 2023-07-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0011_rename_user_organization_name_user_profile_user_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization'),
        ),
    ]
