# Generated by Django 4.2.1 on 2023-07-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authenticationApp",
            "0011_user_profile_district_user_profile_division_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name_plural": "User (Staff, HDO, Admin, User, Superuser)"
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="is_cso",
            field=models.BooleanField(default=False, verbose_name="is_hdo"),
        ),
    ]
