# Generated by Django 4.2 on 2023-07-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0013_alter_user_signin_token_tms_token_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User (Staff, HDO, Admin, User, Superuser)'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_cso',
            field=models.BooleanField(default=False, verbose_name='is_hdo'),
        ),
    ]
