# Generated by Django 4.2 on 2024-01-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSOConnectedChannels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cso_email",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="HDO email"
                    ),
                ),
                ("room_slug", models.CharField(max_length=60)),
                ("channel_value", models.CharField(max_length=74)),
            ],
            options={"verbose_name_plural": "HDO Channels (inside System)",},
        ),
        migrations.CreateModel(
            name="CSOOnline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cso_email",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="HDO email"
                    ),
                ),
                ("room_slug", models.CharField(max_length=60)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="HDO active"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Joined at"),
                ),
                (
                    "last_update",
                    models.DateTimeField(auto_now=True, verbose_name="Last activity"),
                ),
                (
                    "user_organization",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Organization",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="District"
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Division"
                    ),
                ),
            ],
            options={"verbose_name_plural": "HDO Online (inside System)",},
        ),
    ]
