# Generated by Django 4.1.7 on 2023-02-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSOConnectedChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cso_email', models.CharField(blank=True, max_length=60, null=True)),
                ('room_slug', models.CharField(max_length=60)),
                ('channel_value', models.CharField(max_length=74)),
            ],
            options={
                'verbose_name_plural': 'CSO Channels (inside System)',
            },
        ),
        migrations.CreateModel(
            name='CSOOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cso_email', models.CharField(blank=True, max_length=60, null=True)),
                ('room_slug', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True, verbose_name='CSO active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined at')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last activity')),
            ],
            options={
                'verbose_name_plural': 'CSO Online (inside System)',
            },
        ),
    ]
