# Generated by Django 4.2.1 on 2023-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csoonline",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="District"
            ),
        ),
        migrations.AddField(
            model_name="csoonline",
            name="division",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Division"
            ),
        ),
        migrations.AddField(
            model_name="csoonline",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="csoonline",
            name="user_organization",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Organization"
            ),
        ),
    ]
