# Generated by Django 4.2.1 on 2023-07-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffApp", "0002_csoonline_district_csoonline_division_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="csoconnectedchannels",
            options={"verbose_name_plural": "HDO Channels (inside System)"},
        ),
        migrations.AlterModelOptions(
            name="csoonline",
            options={"verbose_name_plural": "HDO Online (inside System)"},
        ),
    ]
