# Generated by Django 4.2 on 2023-07-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0004_alter_csoconnectedchannels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csoconnectedchannels',
            options={'verbose_name_plural': 'HDO Channels (inside System)'},
        ),
    ]
